# Generated by Django 4.2.1 on 2023-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('temperatura', models.FloatField()),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
            ],
        ),
    ]
